### ISSUE TITLE
AttributeError: 'str' object has no attribute 'suffix'

### ISSUE THREAD

**Issue by Jules-WinnfieldX** [sltipirate/ofscraper#11]
```
Downloading to C:\Users\<user>\Data\ofscraper/{model_username}/{responsetype}/{mediatype}/


Progress: (0 photos, 0 videos, 0 skipped || 0): 0it [00:00, ?it/s]Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1583, in stream    yield response
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python311\Lib\site-packages\src\utils\download.py", line 259, in download_paid
    temp=trunicate(f"{filename}")
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python311\Lib\site-packages\src\utils\download.py", line 349, in trunicate
    ext=str(path.suffix)
            ^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'suffix'

Progress: (0 photos, 0 videos, 1 skipped || 0.0 MB): : 1it [00:00,  1.21it/s]Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1583, in stream    yield response
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python311\Lib\site-packages\src\utils\download.py", line 259, in download_paid
    temp=trunicate(f"{filename}")
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python311\Lib\site-packages\src\utils\download.py", line 349, in trunicate
    ext=str(path.suffix)
            ^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'suffix'
```

Error is thrown during a run with args `ofscraper --purchased --username ALL`

**Comment by sltipirate** [comment]
I added a line in the latest 
commit to fix this 
or version 1.75 I believe

**Comment by Jules-WinnfieldX** [comment]
Can confirm, fixed. Thanks
